-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS pos."Products"
(
    product_id integer NOT NULL,
    product_name character varying(255) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    unit character varying(255) COLLATE pg_catalog."default",
    price numeric(10, 2),
    category character varying(255) COLLATE pg_catalog."default" NOT NULL,
    printer character varying(255) COLLATE pg_catalog."default",
    sprice character varying(255) COLLATE pg_catalog."default",
    category_id integer,
    CONSTRAINT "Products_pkey" PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS pos."Order_Products"
(
    order_product_id integer NOT NULL DEFAULT nextval('pos."Order_Products_order_product_id_seq"'::regclass),
    order_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT "Order_Products_pkey" PRIMARY KEY (order_product_id),
    CONSTRAINT order_product_unique UNIQUE (order_id, product_id)
);

CREATE TABLE IF NOT EXISTS pos."Orders"
(
    order_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    customer_id integer,
    order_date timestamp with time zone,
    total_amount numeric(10, 2),
    table_number integer,
    order_type character varying(255) COLLATE pg_catalog."default",
    created_by integer,
    CONSTRAINT "Orders_pkey" PRIMARY KEY (order_id),
    CONSTRAINT unique_table_number UNIQUE (table_number)
);

CREATE TABLE IF NOT EXISTS pos."Users"
(
    user_id integer NOT NULL,
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    firstname character varying(255) COLLATE pg_catalog."default" NOT NULL,
    lastname character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(255) COLLATE pg_catalog."default",
    address character varying(255) COLLATE pg_catalog."default",
    phone character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT "Users_pkey" PRIMARY KEY (user_id),
    CONSTRAINT constraint_name UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS pos."Table_Assignments"
(
    assignment_id integer NOT NULL DEFAULT nextval('pos."Table_Assignments_assignment_id_seq"'::regclass),
    table_number integer NOT NULL,
    user_id integer NOT NULL,
    assigned_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Table_Assignments_pkey" PRIMARY KEY (assignment_id)
);

CREATE TABLE IF NOT EXISTS pos."Categories"
(
    category_id serial,
    category_name character varying(255) NOT NULL,
    parent_category_id integer REFERENCES pos."Categories"(category_id),
    color character varying(10),
    PRIMARY KEY (category_id)
);

ALTER TABLE IF EXISTS pos."Products"
    ADD COLUMN category_id INT REFERENCES pos."Categories"(category_id)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS pos."Order_Products"
    ADD CONSTRAINT "Order_Products_order_id_fkey" FOREIGN KEY (order_id)
    REFERENCES pos."Orders" (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS pos."Order_Products"
    ADD CONSTRAINT "Order_Products_product_id_fkey" FOREIGN KEY (product_id)
    REFERENCES pos."Products" (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS pos."Orders"
    ADD CONSTRAINT "Orders_created_by_fkey" FOREIGN KEY (created_by)
    REFERENCES pos."Users" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS pos."Table_Assignments"
    ADD CONSTRAINT "Table_Assignments_table_number_fkey" FOREIGN KEY (table_number)
    REFERENCES pos."Orders" (table_number) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS pos."Table_Assignments"
    ADD CONSTRAINT "Table_Assignments_user_id_fkey" FOREIGN KEY (user_id)
    REFERENCES pos."Users" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;